#!/usr/bin/python3
"""Small, dependency-free administration UI for Forkcastra."""
import argparse
import hashlib
import hmac
import json
import os
import secrets
import sqlite3
import subprocess
import time
import platform
import shutil
from http import cookies
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

DB = Path(os.environ.get("FORKCASTRA_PANEL_DB", "/var/lib/forkcastra/panel.db"))
STATIC = Path(os.environ.get("FORKCASTRA_PANEL_STATIC", "/usr/share/forkcastra/panel"))
SESSION_TTL = 8 * 60 * 60


def connect():
    DB.parent.mkdir(parents=True, exist_ok=True)
    db = sqlite3.connect(DB)
    db.execute("CREATE TABLE IF NOT EXISTS users (username TEXT PRIMARY KEY, salt BLOB NOT NULL, digest BLOB NOT NULL)")
    db.execute("CREATE TABLE IF NOT EXISTS sessions (token_hash BLOB PRIMARY KEY, username TEXT NOT NULL, csrf TEXT NOT NULL, expires INTEGER NOT NULL)")
    db.execute("""CREATE TABLE IF NOT EXISTS channels (
        id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL,
        input_url TEXT NOT NULL, output_url TEXT NOT NULL,
        enabled INTEGER NOT NULL DEFAULT 1, created INTEGER NOT NULL
    )""")
    columns = {row[1] for row in db.execute("PRAGMA table_info(channels)")}
    migrations = {
        "input_type": "TEXT NOT NULL DEFAULT 'url'", "adapter": "INTEGER",
        "delivery": "TEXT", "frequency": "INTEGER", "polarization": "TEXT",
        "symbolrate": "INTEGER", "pnr": "INTEGER", "lnb": "TEXT"
    }
    for name, definition in migrations.items():
        if name not in columns:
            db.execute("ALTER TABLE channels ADD COLUMN %s %s" % (name, definition))
    db.execute("DELETE FROM sessions WHERE expires < ?", (int(time.time()),))
    db.commit()
    return db


def password_digest(password, salt):
    return hashlib.scrypt(password.encode(), salt=salt, n=16384, r=8, p=1, dklen=32)


def create_admin(username):
    import getpass
    if not username or len(username) > 64:
        raise SystemExit("Invalid username")
    first = getpass.getpass("New panel password: ")
    second = getpass.getpass("Repeat password: ")
    if first != second or len(first) < 12:
        raise SystemExit("Passwords differ or contain fewer than 12 characters")
    salt = secrets.token_bytes(16)
    with connect() as db:
        db.execute("INSERT OR REPLACE INTO users VALUES (?, ?, ?)", (username, salt, password_digest(first, salt)))
    print("Administrator created. Start forkcastra-panel.service")


def service_state():
    try:
        result = subprocess.run(["systemctl", "is-active", "forkcastra.service"], text=True, capture_output=True, timeout=3)
        return result.stdout.strip() or "unknown"
    except (OSError, subprocess.TimeoutExpired):
        return "unknown"


def valid_url(value, allowed):
    if not isinstance(value, str) or not 4 <= len(value) <= 1024 or "\n" in value or "\r" in value:
        return False
    return any(value.startswith(scheme + "://") for scheme in allowed)


def lua_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_config(rows):
    lines = ["-- Generated by Forkcastra Panel. Do not edit.", 'dofile("/usr/share/forkcastra/stream.lua")', ""]
    for row in rows:
        channel_id, name, input_url, output_url, enabled, input_type, adapter, delivery, frequency, polarization, symbolrate, pnr, lnb = row
        if input_type == "dvb":
            fields = ["type = %s" % lua_string(delivery), "adapter = %d" % adapter, "frequency = %d" % frequency]
            if polarization: fields.append("polarization = %s" % lua_string(polarization))
            if symbolrate: fields.append("symbolrate = %d" % symbolrate)
            if pnr: fields.append("pnr = %d" % pnr)
            if lnb: fields.append("lnb = %s" % lua_string(lnb))
            input_lua = "{ " + ", ".join(fields) + " }"
        else:
            input_lua = lua_string(input_url)
        lines.extend(["make_channel({", "    name = %s," % lua_string(name),
            "    enable = %s," % ("true" if enabled else "false"),
            "    input = { %s }," % input_lua, "    output = { %s }," % lua_string(output_url), "})", ""])
    return "\n".join(lines)


def system_info():
    uptime = 0
    memory_total = memory_available = 0
    try:
        uptime = int(float(Path("/proc/uptime").read_text().split()[0]))
        values = {}
        for line in Path("/proc/meminfo").read_text().splitlines():
            key, value = line.split(":", 1)
            values[key] = int(value.strip().split()[0]) * 1024
        memory_total, memory_available = values.get("MemTotal", 0), values.get("MemAvailable", 0)
    except (OSError, ValueError):
        pass
    disk = shutil.disk_usage("/")
    try:
        load = list(os.getloadavg())
    except OSError:
        load = [0, 0, 0]
    return {"hostname": platform.node(), "kernel": platform.release(), "python": platform.python_version(),
            "uptime": uptime, "load": load, "memory_total": memory_total,
            "memory_used": max(0, memory_total - memory_available), "disk_total": disk.total,
            "disk_used": disk.used}


def playlist(rows):
    lines = ["#EXTM3U"]
    for name, output in rows:
        lines.extend(["#EXTINF:-1,%s" % name.replace("\n", " "), output])
    return "\n".join(lines) + "\n"


def apply_channels():
    with connect() as db:
        rows = db.execute("SELECT id,name,input_url,output_url,enabled,input_type,adapter,delivery,frequency,polarization,symbolrate,pnr,lnb FROM channels ORDER BY id").fetchall()
    target = DB.parent / "generated.lua"
    temporary = target.with_suffix(".tmp")
    temporary.write_text(render_config(rows), encoding="utf-8")
    os.chmod(temporary, 0o640)
    os.replace(temporary, target)
    result = subprocess.run(["sudo", "/usr/lib/forkcastra/apply-config"], text=True, capture_output=True, timeout=15)
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "could not apply configuration")


class Handler(BaseHTTPRequestHandler):
    server_version = "ForkcastraPanel/0.1"

    def log_message(self, fmt, *args):
        print("%s - %s" % (self.address_string(), fmt % args), flush=True)

    def send_headers(self, status=200, content_type="application/json; charset=utf-8", cookie=None):
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Cache-Control", "no-store")
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "DENY")
        self.send_header("Referrer-Policy", "no-referrer")
        self.send_header("Content-Security-Policy", "default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'")
        if cookie:
            self.send_header("Set-Cookie", cookie)
        self.end_headers()

    def body(self):
        length = int(self.headers.get("Content-Length", "0"))
        if length > 16384:
            raise ValueError("request too large")
        return self.rfile.read(length)

    def session(self):
        jar = cookies.SimpleCookie(self.headers.get("Cookie", ""))
        morsel = jar.get("forkcastra_session")
        if not morsel:
            return None
        token_hash = hashlib.sha256(morsel.value.encode()).digest()
        with connect() as db:
            return db.execute("SELECT username, csrf FROM sessions WHERE token_hash=? AND expires>=?", (token_hash, int(time.time()))).fetchone()

    def json(self, data, status=200, cookie=None):
        self.send_headers(status, cookie=cookie)
        self.wfile.write(json.dumps(data).encode())

    def file(self, name, content_type):
        path = STATIC / name
        try:
            data = path.read_bytes()
        except OSError:
            self.send_error(404)
            return
        self.send_headers(200, content_type)
        self.wfile.write(data)

    def do_HEAD(self):
        if self.path in ("/", "/index.html"):
            return self.send_headers(200, "text/html; charset=utf-8")
        self.send_error(404)

    def do_GET(self):
        if self.path in ("/", "/index.html"):
            return self.file("index.html", "text/html; charset=utf-8")
        if self.path == "/app.css":
            return self.file("app.css", "text/css; charset=utf-8")
        if self.path == "/app.js":
            return self.file("app.js", "application/javascript; charset=utf-8")
        if self.path == "/api/session":
            session = self.session()
            return self.json({"authenticated": bool(session), "username": session[0] if session else None, "csrf": session[1] if session else None})
        if self.path == "/api/status":
            session = self.session()
            if not session:
                return self.json({"error": "unauthorized"}, 401)
            config = Path("/etc/forkcastra/forkcastra.lua")
            with connect() as db:
                count = db.execute("SELECT count(*) FROM channels").fetchone()[0]
            return self.json({"service": service_state(), "config": str(config), "configured": config.exists(), "version": "4.0.282-6", "channels": count})
        if self.path == "/api/channels":
            if not self.session():
                return self.json({"error": "unauthorized"}, 401)
            with connect() as db:
                rows = db.execute("SELECT id,name,input_url,output_url,enabled,input_type,adapter,delivery,frequency,polarization,symbolrate,pnr,lnb FROM channels ORDER BY id DESC").fetchall()
            keys = ("id","name","input","output","enabled","input_type","adapter","delivery","frequency","polarization","symbolrate","pnr","lnb")
            return self.json({"channels": [dict(zip(keys, r)) for r in rows]})
        if self.path == "/api/adapters":
            if not self.session():
                return self.json({"error": "unauthorized"}, 401)
            adapters = []
            for directory in sorted(Path("/dev/dvb").glob("adapter*")):
                try: number = int(directory.name.replace("adapter", ""))
                except ValueError: continue
                nodes = sorted(item.name for item in directory.iterdir())
                frontends = [name for name in nodes if name.startswith("frontend")]
                adapters.append({"adapter": number, "path": str(directory), "frontends": frontends, "nodes": nodes})
            return self.json({"adapters": adapters})
        if self.path in ("/api/outputs", "/playlist.m3u", "/playlist.m3u8"):
            if not self.session():
                return self.json({"error": "unauthorized"}, 401)
            with connect() as db:
                rows = db.execute("SELECT name,output_url FROM channels WHERE enabled=1 ORDER BY id").fetchall()
            if self.path == "/api/outputs":
                return self.json({"outputs": [{"name": row[0], "url": row[1], "protocol": row[1].split(":", 1)[0].upper()} for row in rows]})
            data = playlist(rows).encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "application/vnd.apple.mpegurl; charset=utf-8")
            self.send_header("Content-Disposition", "attachment; filename=forkcastra%s" % (".m3u8" if self.path.endswith("m3u8") else ".m3u"))
            self.send_header("Content-Length", str(len(data)))
            self.end_headers()
            return self.wfile.write(data)
        if self.path == "/api/system":
            if not self.session():
                return self.json({"error": "unauthorized"}, 401)
            return self.json(system_info())
        self.send_error(404)

    def do_POST(self):
        try:
            data = json.loads(self.body() or b"{}")
        except (ValueError, json.JSONDecodeError):
            return self.json({"error": "invalid request"}, 400)
        if self.path == "/api/login":
            username = str(data.get("username", ""))
            password = str(data.get("password", ""))
            with connect() as db:
                user = db.execute("SELECT salt, digest FROM users WHERE username=?", (username,)).fetchone()
                valid = user and hmac.compare_digest(password_digest(password, user[0]), user[1])
                if not valid:
                    time.sleep(0.4)
                    return self.json({"error": "invalid credentials"}, 401)
                token, csrf = secrets.token_urlsafe(32), secrets.token_urlsafe(24)
                db.execute("INSERT INTO sessions VALUES (?, ?, ?, ?)", (hashlib.sha256(token.encode()).digest(), username, csrf, int(time.time()) + SESSION_TTL))
            cookie = "forkcastra_session=%s; Path=/; HttpOnly; SameSite=Strict; Max-Age=%d" % (token, SESSION_TTL)
            return self.json({"ok": True, "csrf": csrf}, cookie=cookie)
        if self.path == "/api/logout":
            session = self.session()
            if session and hmac.compare_digest(str(data.get("csrf", "")), session[1]):
                jar = cookies.SimpleCookie(self.headers.get("Cookie", ""))
                token = jar["forkcastra_session"].value
                with connect() as db:
                    db.execute("DELETE FROM sessions WHERE token_hash=?", (hashlib.sha256(token.encode()).digest(),))
            return self.json({"ok": True}, cookie="forkcastra_session=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0")
        session = self.session()
        if not session or not hmac.compare_digest(str(data.get("csrf", "")), session[1]):
            return self.json({"error": "unauthorized"}, 401)
        if self.path == "/api/channels":
            name = str(data.get("name", "")).strip()
            input_type = str(data.get("input_type", "url"))
            input_url = str(data.get("input", "")).strip()
            output_url = str(data.get("output", "")).strip()
            if not 1 <= len(name) <= 120 or not valid_url(output_url, ("udp", "http", "file")):
                return self.json({"error": "invalid channel data"}, 400)
            dvb = [None] * 7
            if input_type == "dvb":
                try:
                    adapter, frequency = int(data.get("adapter")), int(data.get("frequency"))
                    symbolrate = int(data["symbolrate"]) if data.get("symbolrate") else None
                    pnr = int(data["pnr"]) if data.get("pnr") else None
                except (TypeError, ValueError):
                    return self.json({"error": "invalid DVB parameters"}, 400)
                delivery = str(data.get("delivery", "S2")).upper()
                polarization = str(data.get("polarization", "")).upper() or None
                lnb = str(data.get("lnb", "")).strip() or None
                if adapter < 0 or not 1000 <= frequency <= 15000000 or delivery not in ("S","S2","T","T2","C","ATSC","ISDBT") or (polarization and polarization not in ("H","V","L","R")):
                    return self.json({"error": "DVB parameters out of range"}, 400)
                dvb = [adapter, delivery, frequency, polarization, symbolrate, pnr, lnb]
                input_url = "dvb://adapter%d" % adapter
            elif not valid_url(input_url, ("udp", "http", "file")):
                return self.json({"error": "invalid input URL"}, 400)
            with connect() as db:
                cursor = db.execute("INSERT INTO channels(name,input_url,output_url,enabled,created,input_type,adapter,delivery,frequency,polarization,symbolrate,pnr,lnb) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)", (name, input_url, output_url, 1, int(time.time()), input_type, *dvb))
            return self.json({"ok": True, "id": cursor.lastrowid}, 201)
        if self.path == "/api/apply":
            try:
                apply_channels()
                return self.json({"ok": True, "service": service_state()})
            except (OSError, subprocess.TimeoutExpired, RuntimeError) as error:
                return self.json({"error": str(error)}, 500)
        self.send_error(404)

    def do_DELETE(self):
        session = self.session()
        csrf = self.headers.get("X-CSRF-Token", "")
        if not session or not hmac.compare_digest(csrf, session[1]):
            return self.json({"error": "unauthorized"}, 401)
        if not self.path.startswith("/api/channels/"):
            return self.send_error(404)
        try:
            channel_id = int(self.path.rsplit("/", 1)[1])
        except ValueError:
            return self.json({"error": "invalid id"}, 400)
        with connect() as db:
            cursor = db.execute("DELETE FROM channels WHERE id=?", (channel_id,))
        return self.json({"ok": bool(cursor.rowcount)})


def main():
    parser = argparse.ArgumentParser(description="Forkcastra administration panel")
    parser.add_argument("--create-admin", metavar="USERNAME")
    parser.add_argument("--bind", default=os.environ.get("FORKCASTRA_PANEL_BIND", "0.0.0.0"))
    parser.add_argument("--port", type=int, default=int(os.environ.get("FORKCASTRA_PANEL_PORT", "8088")))
    args = parser.parse_args()
    if args.create_admin:
        create_admin(args.create_admin)
        return
    connect().close()
    server = ThreadingHTTPServer((args.bind, args.port), Handler)
    print("Forkcastra panel listening on %s:%d" % (args.bind, args.port), flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
